variable "name" {}
variable "pipeline_arn" {}
variable "s3_bucket" {}
variable "build_name" {}
variable "FullRepositoryId" {}
variable "BranchName" {}
variable "ConnectionArn" {}
variable "BuildProjectName" {}
variable "Provider" {}
variable "EnvironmentName" {}